version: '3.8'

services:
  app:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - todo-app-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_pFn9yLNX5Mrd
      - POSTGRES_DB=ep-autumn-morning-a16wd1l7-pooler.ap-southeast-1.aws.neon.tech
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo-app-network

volumes:
  postgres_data:

networks:
  todo-app-network:
    external: true
